FROM erlang:27-slim

RUN apt-get update && apt-get install -y make git locales && rm -rf /var/lib/apt/lists/* \
    && sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

WORKDIR /app

# Install rebar3
RUN git clone https://github.com/erlang/rebar3.git /tmp/rebar3 && \
    cd /tmp/rebar3 && ./bootstrap && \
    install -m 755 /tmp/rebar3/rebar3 /usr/local/bin/rebar3 && \
    rm -rf /tmp/rebar3

COPY rebar.config ./
RUN rebar3 get-deps || true

COPY . .

CMD ["make", "local-test"]
